#pragma once

#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include "vecdata.h"
#include <functional>
#include <highfive/highfive.hpp>
#include "utils.h"  // VarDescriptor现在定义在utils.h中
#include "dparam_semantics.h"
#include "func_table.cuh"
using namespace std;

class HelioXroupData;
namespace coreneuron {
struct CoreData;
}

//继承了这类后，便可以将自己的变量映射到全局变量中
class VarMapAble
{
public:
    // 使用VarDescriptor统一接口，简化参数传递
    // descriptor包含: mech, var, node_or_mech_idx, array_index
    // mode参数独立出来因为同一个descriptor在CPU/GPU可能都需要访问
    virtual double *getVarPtr(const VarDescriptor& descriptor, Mode mode) { return nullptr; }
};


//这三个是仿真时调用Mechanism的时候传入的参数
struct SimMechInitialParam{
    double *v;
    double dt;
};
struct SimMechCurrentParam{
    double *v;
    double *d;
    double *rhs;
    double t;
};  
struct SimMechStateParam{
    double *v;
    double dt;
    double t;
};

class Mechanism : public VarMapAble
{
public:
    int type;
    string name;
    bool need_area;
    bool write_state_ion;// 这个mech是否需要在state写离子浓度
    Mode mode;
    int *permute=nullptr;//permute数组
    // 记录变量相关的数据

    VecData<double> *vecdata_area; // 由外部函数生成，自己不要初始化！
    // 初始化的第一阶段，初始化一些基本的参数
    Mechanism(MechInitParams &param);

    virtual ~Mechanism();

    // 有一些情况下，在析构函数中不能释放内存，这会导致在函数传参时重复析构
    virtual void cleanUp();

    /*
     * decide which indicies this mechanism belong
     * allocate memory for this mech and set default values
     * node_count: number of node which this mech is reponsible for
     * buf: nodeindices generated by NEURON
     * 类似于初始化的第二阶段
     */
    virtual void reg_node_indices(MechInitParams &param) = 0;

    /*
     * read mechansim from CoreNEURON data
     * data: mechanism data on CoreNEURON
     * nnode: node number that hold this mechanism
     * param_size: number of parameters in this mechanism
     * 类似于初始化的第三阶段
     */
    virtual void read_data_from_coredat(MechInitParams &param) = 0;

    /*initialize the state variables
     *v_init: initial voltage*/
    virtual void initialize_cpu(SimMechInitialParam &param) = 0;
    virtual void initialize_gpu(SimMechInitialParam &param) = 0;

    /*
     * compute ion current
     * v: voltages of all comparments
     * dt: time step
     */
    virtual void current_cpu(SimMechCurrentParam &param) = 0;
    virtual void current_gpu(SimMechCurrentParam &param) = 0;
    virtual void sync_gpu() = 0;

    /*
     * solve the diffirential equation of state variables
     * update the state variables by one step
     */
    virtual void state_cpu(SimMechStateParam &param) = 0;
    virtual void state_gpu(SimMechStateParam &param) = 0;

    // Optional post-init stage: resolve POINTER targets to concrete addresses.
    // Called after all mechanisms have been created and their variable tables
    // are available (so cross-mechanism POINTERs can be resolved).
    virtual void resolve_pointers(HelioXroupData* /*ndat*/, coreneuron::CoreData* /*cdat*/) {}

    // protected:
    int nnode;                                          // number of nodes that this ion channel responsible for
    std::unique_ptr<VecData<int>> vecdata_node_indices; // compartment indices that this ion channel responsible for ,是reg_node的时候从coredat里面拷贝过来的
    std::unique_ptr<VecData<double>> vecdata_g_mech;    // conductance
    std::unique_ptr<VecData<double>> vecdata_i_mech;    // current

    double celsius;
    void *cuda_stream;
    // Reusable CUDA event for cross-stream dependency management.
    // Stored as an opaque pointer to avoid including CUDA headers here.
    void *cuda_event = nullptr;
};

class MechanismFactory
{
public:
    using Creator = std::function<Mechanism *(MechInitParams &)>;

    static MechanismFactory &getInstance()
    {
        static MechanismFactory instance;
        return instance;
    }
    void registerMechanism(const std::string &name, Creator creator);
    void registerVarMap(const std::string &name, VarMapAble *varMap);
    void registerPntReceiveSize(const std::string &name, int pnt_receive_size);
    // Register the dparam (pdata) slot indices that correspond to POINTER variables for this mechanism.
    // Slots must be in the same order as the mechanism's POINTER variables (trait enum order).
    void registerPointerDparamSlots(const std::string& name, std::vector<int> slots);
    // Optional dparam semantics (CoreNEURON-style).
    // Length must match bbcore dparam size for the mechanism type. Encoding is compatible with NEURON:
    // See `DparamSemantics` in `src/utils/dparam_semantics.h`.
    void registerDparamSemantics(const std::string& name, std::vector<int> semantics);
    Mechanism *createMechanism(const std::string &name, MechInitParams &initParam);
    VarMapAble *getVarMap(const std::string &name);
    int getPntReceiveSize(const std::string &name);
    const std::vector<int>* getPointerDparamSlots(const std::string& name) const;
    const std::vector<int>* getDparamSemantics(const std::string& name) const;

private:
    std::unordered_map<std::string, Creator> registry_;
    std::vector<Mechanism *> allocatedMechanisms_;
    std::unordered_map<int, std::string> type2name_;
    std::unordered_map<std::string, int> name2type_;
    std::unordered_map<std::string, VarMapAble *> name2varMap_;
    std::unordered_map<std::string, int> name2pntReceiveSize_;
    std::unordered_map<std::string, std::vector<int>> name2pointerDparamSlots_;
    std::unordered_map<std::string, std::vector<int>> name2dparamSemantics_;
    MechanismFactory() = default;
    ~MechanismFactory() = default;
    MechanismFactory(const MechanismFactory &) = delete;
    MechanismFactory &operator=(const MechanismFactory &) = delete;
};

// 注册宏
#define REGISTER_MECHANISM(NAME, CLASS) \
    inline bool CLASS##_registered = []() { \
        MechanismFactory::getInstance().registerMechanism(NAME, [](MechInitParams &param) { return new CLASS(param); }); \
        return true; }();

// 新的后突触注册宏
#define REGISTER_POSTSYN(NAME, CLASS, PNT_RECEIVE_SIZE) \
    inline bool CLASS##_postsyn_registered = []() { \
        MechanismFactory::getInstance().registerMechanism(NAME, [](MechInitParams &param) { return new CLASS(param); }); \
        MechanismFactory::getInstance().registerPntReceiveSize(NAME, PNT_RECEIVE_SIZE); \
        return true; }();

// Macro helpers for unique variable names in registration.
#define HELIOX_CONCAT_INNER(a, b) a##b
#define HELIOX_CONCAT(a, b) HELIOX_CONCAT_INNER(a, b)

// Register POINTER dparam slot indices for a mechanism.
// Example: for a POINT_PROCESS with `POINTER x, y` that ends up in `_ppvar[2]` and `_ppvar[3]`:
//   REGISTER_POINTER_DPARAM_SLOTS("mechname", 2, 3);
#define REGISTER_POINTER_DPARAM_SLOTS(NAME, ...) \
    inline bool HELIOX_CONCAT(_pointer_slots_registered_, __COUNTER__) = []() { \
        MechanismFactory::getInstance().registerPointerDparamSlots(NAME, std::vector<int>{__VA_ARGS__}); \
        return true; }();

// Register optional dparam semantics for a mechanism.
// Example:
//   REGISTER_DPARAM_SEMANTICS("mechname", -1, -6, -5);
#define REGISTER_DPARAM_SEMANTICS(NAME, ...) \
    inline bool HELIOX_CONCAT(_dparam_semantics_registered_, __COUNTER__) = []() { \
        MechanismFactory::getInstance().registerDparamSemantics(NAME, std::vector<int>{__VA_ARGS__}); \
        return true; }();

//
