#ifndef spike_h
#define spike_h

#include <iostream>
#include <cmath>
#include <vector>
#include <queue>

using namespace std;

//typedef pair<int, double> event;
enum class SpikeFlag
{
    INVALID = -1, // invalid spike, i.e. the spike is not valid or not generated yet
    NORMAL_EVENT = 0, // normal spike
    SELF_EVENT = 1, // self event, i.e. the spike is generated by the same neuron
    NETSTIM_INIT_EVENT = 2, // netstim init
};

class Spike
{
    using enum SpikeFlag;
    public:
        Spike()
        {
            gid = -1;
            pre_node_id = -1;
            syn_type = -1;
            syn_id = -1;
            deliver_time = -1.0;
            flag = INVALID; // 0: normal events 1: self events
        }
        Spike(int g, double t, SpikeFlag f) : gid(g), deliver_time(t), flag(f)
        {
            pre_node_id = -1;
            syn_type = -1;
            syn_id = -1;
        }
        Spike(uint32_t stype, uint32_t sid, double t, SpikeFlag f)
        {
            gid = -1;
            pre_node_id = -1;
            syn_type = stype;
            syn_id = sid;
            deliver_time = t;
            flag = f;
        }
        Spike(const Spike &s)
        {
            gid = s.gid;
            pre_node_id = s.pre_node_id;
            syn_type = s.syn_type;
            syn_id = s.syn_id;
            flag = s.flag;
            deliver_time = s.deliver_time;
        }
        int gid;
        int pre_node_id; 
        int syn_type, syn_id; // type and index in Synapse class
        SpikeFlag flag;
        double deliver_time; // spike time + delay
};

class SpikeVector
{
    public:
        uint32_t nspike; // number of spikes in vec_spk
        vector<Spike> v;
        bool hasNewSpk;
        SpikeVector()
        {
            nspike = 0;
            v.reserve(1000); // default size is 1000
            hasNewSpk = false;
        }
        SpikeVector(uint32_t n)
        {
            nspike = 0;
            v.resize(n);
            hasNewSpk = false;
        }

        // use resize in constructor func and directly
        // assign objects to v may be faster
        void push_spike(Spike s)
        {
            v.push_back(s);
            nspike++;
        }

        void set_spike(const Spike &s, int idx)
        {
            // if(idx >= v.size())
            // {
            //     printf("SpikeVector::set_spike: index out of range\n");
            //     printf("idx: %d, size: %d\n", idx, v.size());
            //     assert(0);
            // }
            v[idx] = s;
            hasNewSpk = true;
        }

        void clean()
        {
            Spike empty_spk;
            std::fill(v.begin(), v.end(), empty_spk);
            // memset(v.data(), -1, sizeof(Spike) * v.size());
            nspike = 0;
            hasNewSpk = false;
        }
};

struct cmp
{
    bool operator()(const Spike& e1, const Spike& e2)
    {
        bool result = false;
        if (fabs(e1.deliver_time - e2.deliver_time) > 1e-9)
            result = e1.deliver_time > e2.deliver_time;
        else
        {
            if (e1.syn_type != e2.syn_type)
                result = e1.syn_type > e2.syn_type;
            else
            {
                if (e1.syn_id != e2.syn_id)
                    result = e1.syn_id > e2.syn_id;
                else
                    result = e1.pre_node_id > e2.pre_node_id;
            }
        }
        return result;
    }
};

typedef priority_queue<Spike, vector<Spike>, cmp> SpikeBuffer; // spikes from pre-synapses, format: <pre_node_id, time_to_fire (pre_fire_time + delay)>

#endif
